baseURL = "https://chrisa.github.io/"
languageCode = "en-us"
title = "Chris's Blog"
theme = "noteworthy"
enableRobotsTXT = true
paginate = 4
summaryLength = 15
publishDir = "docs"

googleAnalytics = "UA-201798100-1"

[taxonomies]
  category = "categories"

[params]
  github = "https://github.com/chrisa"
  showReadMore = false

[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true
    disable = false
    respectDoNotTrack = true
    useSessionStorage = false
